name: jam-server-unit-tests

on: push

jobs:
  ubuntu-latest-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: npm ci
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READ_PACKAGE_API_KEY }}

      - name: npm test
        run: npm test
